export const APP_WRITE_ID = '65a47c3fa6b7ea3b8369'
export const DB_ID = 'crm'
export const COLLECTION_DEALS = 'deals'
export const COLLECTION_CUSTOMERS = 'customers'
export const COLLECTION_COMMENTS = 'comments'
export const STORAGE_ID = 'storage'
